services:
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - ./db/volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ShareIt
      - POSTGRES_USER=sa  #dbuser
      - POSTGRES_PASSWORD=password  #12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10