server:
  port: 8080
spring:
  application.name: ShareIt Gateway
  main.banner-mode: OFF
shareit-server:
  url: http://localhost:9090
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG